name: Docker Image CI

on:
  push:
    branches:
      - main  # O la rama que desees para activar el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build Docker image
      run: docker build -t lenny1116/simulador-particulas:latest .

    - name: Push Docker image
      run: docker push lenny1116/simulador-particulas:latest
